//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefCounterAnalyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefCounterAnalyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference counter is consistent.
        /// </summary>
        internal static string RefCounter001AnalyzerDescription {
            get {
                return ResourceManager.GetString("RefCounter001AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ignore return value of type IRefCounter..
        /// </summary>
        internal static string RefCounter001AnalyzerTitle {
            get {
                return ResourceManager.GetString("RefCounter001AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference counter is checkable.
        /// </summary>
        internal static string RefCounter002AnalyzerDescription {
            get {
                return ResourceManager.GetString("RefCounter002AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference counter analyzer is working.
        /// </summary>
        internal static string RefCounter003AnalyzerDescription {
            get {
                return ResourceManager.GetString("RefCounter003AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Return value of IRefCounter must be used.
        /// </summary>
        internal static string RefCounter004AnalyzerDescription {
            get {
                return ResourceManager.GetString("RefCounter004AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Counter of {0} is {1}, detail {2}.
        /// </summary>
        internal static string RefCounterErrorAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RefCounterErrorAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return type of IRefCounter not used, {0}.
        /// </summary>
        internal static string RefCounterNotAssignedMessageFormat {
            get {
                return ResourceManager.GetString("RefCounterNotAssignedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse error, {0}.
        /// </summary>
        internal static string RefCounterParseErrorMessageFormat {
            get {
                return ResourceManager.GetString("RefCounterParseErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Counter of {0} not checked, for {1}.
        /// </summary>
        internal static string RefCounterSkipAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RefCounterSkipAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assigned to other local variables.
        /// </summary>
        internal static string SkipReasonAssignedToOtherLocalVars {
            get {
                return ResourceManager.GetString("SkipReasonAssignedToOtherLocalVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than one AddRef.
        /// </summary>
        internal static string SkipReasonMoreThanOneAddRef {
            get {
                return ResourceManager.GetString("SkipReasonMoreThanOneAddRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than one DelRef.
        /// </summary>
        internal static string SkipReasonMoreThanOneDelRef {
            get {
                return ResourceManager.GetString("SkipReasonMoreThanOneDelRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intialization not supported.
        /// </summary>
        internal static string SkipReasonSupportedInitialization {
            get {
                return ResourceManager.GetString("SkipReasonSupportedInitialization", resourceCulture);
            }
        }
    }
}
